# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 05:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adlink', '0002_auto_20160222_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='adpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('created_at', models.DateField(default=datetime.datetime.now)),
                ('expiry_date', models.DateTimeField(default=datetime.datetime(2016, 3, 24, 5, 40, 59, 957526))),
            ],
        ),
    ]
