# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 10:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adlink', '0003_adpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='adpost',
            name='company',
            field=models.CharField(default=datetime.datetime(2016, 2, 23, 10, 30, 26, 936786, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adpost',
            name='paid_by',
            field=models.CharField(default=datetime.datetime(2016, 2, 23, 10, 30, 34, 30043, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adpost',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 24, 10, 30, 19, 560037)),
        ),
    ]
