# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 10:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adlink', '0004_auto_20160223_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adpost',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 24, 4, 31, 24, 260894)),
        ),
    ]
