# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 10:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adlink', '0005_auto_20160223_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adpost',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 24, 10, 34, 19, 371749, tzinfo=utc)),
        ),
    ]
