# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 18:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adlink', '0007_auto_20160224_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='clerk_auth',
            name='email',
            field=models.CharField(default='nguruben@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adpost',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 26, 18, 46, 51, 897466, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='adpost',
            name='image',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
    ]
