# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 10:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adlink', '0011_auto_20160301_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adpost',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 31, 10, 0, 51, 821916, tzinfo=utc)),
        ),
    ]
