# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 12:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adlink', '0015_auto_20160301_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adpost',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 3, 12, 31, 32, 600615, tzinfo=utc)),
        ),
    ]
